
apiVersion: v1
kind: Pod
metadata:
  name: app-config
spec:
  containers:
  - name: redis
    image: redis
    imagePullPolicy: Always
    volumeMounts:
    - name: config-volume
      mountPath: /config
    env:
    - name: CONFIGMAP_PARAM
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: config-param
    restartPolicy: Never
  volumes:
  - name: config-volume
    configMap:
      name: app-config

