apiVersion: v1
kind: Pod
metadata:
  name: nginx-debian-pod
spec:
  restartPolicy: Never
  containers:
  - name: nginx
    image: nginx
  - name: debian
    image: debian
    command: ['sleep', '3600']
